---
# tasks file for docker | Debian

- name: Debian | Ensure group "{{ docker_group }}" exists.
  group:
    name: "{{ docker_group }}"
    state: "{{ docker_group_desired_state }}"

- name: Debian | Ensure user "{{ docker_user }}" with group "{{ docker_group }}" exists.
  user:
    name: "{{ docker_user }}"
    comment: Docker user
    group: "{{ docker_group }}"
    home: "{{ docker_user_home }}"
    shell: "{{ docker_user_shell }}"
    state: "{{ docker_user_desired_state }}"

- name: Debian | Installing {{ docker_debian_pre_reqs }}
  apt:
    name: "{{ docker_debian_pre_reqs }}"
    state: "{{ docker_debian_pre_reqs_desired_state }}"
    force_apt_get: yes
    update_cache: yes

- name: Debian | Ensure docker gpg key exists.
  apt_key:
    url: "{{ docker_repo_gpg_key }}"
    state: present

- name: Debian | Adding docker repository.
  apt_repository:
    repo: "{{ docker_repo_debian }}"
    state: "{{ docker_repo_debian_desired_state }}"
    filename: "{{ docker_repo_debian_filename }}"
    codename: "{{ ansible_lsb['codename'] }}"
    update_cache: yes

- name: Debian | Installing {{ docker_apps }}
  apt:
    name: "{{ docker_apps }}"
    state: "{{ docker_apps_desired_state }}"
    force_apt_get: yes
  notify:
    - "set_{{ docker_service_name }}_service_state"
    - "set_{{ docker_service_name }}_service_boot_state"
